name: Build

on:
  push:
    branches: [ "master" ]
  pull_request: {}

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Set Up JDK 17
        id: set-up-java
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 17
          distribution: zulu

      - name: Set Up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Echo java
        run: which java

      - name: Echo java path
        run: echo "${{ steps.set-up-java.outputs.path }}"

      - name: Run Build
        run: ./gradlew build --info
