name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Set Up JDK 17
        id: set-up-java
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 17
          distribution: zulu

      - name: Set Up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Build
        run: ./gradlew build -PmctestJava="${{ steps.set-up-java.outputs.path }}/bin/java"
