name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Set Up JDK 17
        id: set-up-java
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 17
          distribution: zulu

      - name: Set Up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Publish
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
